### ISSUE TITLE
204 response without content

### ISSUE THREAD

**Issue by EricSmekens** [turkerdev/fastify-type-provider-zod#76]
Currently, fastify-swagger allows the specification of a 204 without any content:

https://github.com/fastify/fastify-swagger?tab=readme-ov-file#empty-body-responses
```
{
  response: {
    204: {
      type: 'null',
      description: 'No Content'
    },
    503: {
      type: 'null',
      description: 'Service Unavailable'
    }
  }
}
```

However, when you do this together with this library, that results in a error:

```
"err": {
    "type": "Error",
    "message": "Invalid schema passed: {\"type\":\"null\",\"description\":\"No Content\"}",
    "stack": "Error: Invalid schema passed: {\"type\":\"null\",\"description\":\"No Content\"}
   at resolveSchema (--\\node_modules\\fastify-type-provider-zod\\dist\\index.js:116:11)
   at Object.transform (--\\node_modules\\fastify-type-provider-zod\\dist\\index.js:72:32)
   at Object.swagger (--\\node_modules\\@fastify\\swagger\\lib\\spec\\openapi\\index.js:36:21)
   at fastify.route.handler (--\\node_modules\\@fastify\\swagger-ui\\lib\\routes.js:175:28)
   at preHandlerCallback (--\\node_modules\\fastify\\lib\\handleRequest.js:137:37)
   at validationCompleted (--\\node_modules\\fastify\\lib\\handleRequest.js:121:5)
   at preValidationCallback (--\\node_modules\\fastify\\lib\\handleRequest.js:98:5)
   at handler (--\\node_modules\\fastify\\lib\\handleRequest.js:75:7)
   at handleRequest (--\\node_modules\\fastify\\lib\\handleRequest.js:24:5)
   at runPreParsing (--\\node_modules\\fastify\\lib\\route.js:593:5)"
}
```

**Comment by anthonyvii27** [comment]
Yes, I'm here with the same issue. Commenting to receive news about this functionality.

**Comment by StrangeBytesDev** [comment]
You can do
`response: z.null().describe('No Content')`

**Comment by mjgui** [comment]
Hi, facing the same issue here. 
For context, what we're trying to do is to have our generated OpenAPI document be consumed by a SDK generator. 

From what I can tell, the generated schema for `z.null().description("No content")` in the `.json` file takes the following shape:
```json
{
  "enum":["null"],
  "nullable":true,
  "description":"No content"
}
```
as opposed to 
```json
{
   "type": "null",
  "description":"No content"
}
```

It seems like the relevant section is [here](https://github.com/turkerdev/fastify-type-provider-zod/blob/63bc5a3e9ea52dd1c26c3b34d39eb182c08ee6ee/src/zod-to-json.ts):

```typescript
const zodToJsonSchemaOptions = {
  target: 'openApi3',
  $refStrategy: 'none',
} as const
```

While OpenAPI 3.0 doesn't actually support a `null` type, it seems like `fastify-swagger` does expect that shape.

Not sure where in the chain this problem should be fixed!
